### ISSUE TITLE
Swipe support for mobile device

### ISSUE THREAD

**Issue by geasisland** [p-m-p/jquery-box-slider#15]
Hi There, 

Do you have any plan to update this for mobile device? 
I put slider id as next, prev and change code on box-slider.jquery.js as swipeleft for next, swiperight for prev.

but, with autoscroll function when I swipe the slider it is interrupted by the autoscroll (because of it doesn't pause during i'm playing with it.)

If you have any plan to support this soon. will be awesome!

**Comment by p-m-p** [comment]
Responsive work done. Swipe support with be tracked on #20
