### ISSUE TITLE
TypeError: document.body is null 

### ISSUE THREAD

**Issue by avconsbn** [p-m-p/jquery-box-slider#22]
box-slider-all.jquery.min.js + Joomla 3.4.1
TypeError: document.body is null 

FireBug shows at this location:
{var e=document.body.style,t="";return"webkit...

How to fix?
Thank you.

**Comment by p-m-p** [comment]
What browser do you see this in?

**Comment by avconsbn** [comment]
Firefox 37.0.2
I use box-slider-all.jquery.min.js + CMS Joomla 3.4.1

**Comment by p-m-p** [comment]
I'd need to see a live example of this to be able to help but you may want to try including the script at the bottom of the page instead of in the document head.
