### ISSUE TITLE
Awful coding! aweful

### ISSUE THREAD

**Issue by Taurus-Master** [p-m-p/jquery-box-slider#23]
Please, for god sake before you right down some code , do just few, just few research about other developer and how they doing, thanks

**Comment by cpowell4912** [comment]
Agree, it is really bad. Was not aware it went out. Thanks for letting me
know.

**Comment by p-m-p** [comment]
What's the purpose of this conversation? Why this issue?

**Comment by cpowell4912** [comment]
And why are you writing me?

**Comment by p-m-p** [comment]
Because this is an issue raised on one of my code repositories?!

**Comment by Taurus-Master** [comment]
because by changing some of your code and spending some time, like 3-7 days you can finish your work in the very good way, i did like your work but the problem was coding and if your saying no more developing that's fine, thanks for developing it until this level

**Comment by p-m-p** [comment]
@Taurus-Master if you're comments are directed at myself then please by all means take my code and do as you wish for yourself. If you have constructive criticism that's fine, I'm always open to suggestions for improvement, but I'd suggest you try and more subtle approach to that of blatant trolling :trollface:

**Comment by Taurus-Master** [comment]
@p-m-p I'll keep that in mind
