### ISSUE TITLE
How to reverse vertical 3d scroll when click the pagination items

### ISSUE THREAD

**Issue by minhhoang** [p-m-p/jquery-box-slider#24]
Hi there, 
I would like to reverse the vertical 3d scroll (just like the previous arrow does) when I click the pagination dot icon which has the data-slideindex smaller than the current data-slideindex.
Does everyone have any idea of how to do it?
Thanks in advance.

http://philparsons.co.uk/demos/box-slider/

**Comment by p-m-p** [comment]
Wouldn't be too hard to do, just need to check the current index against the slide you wish to go to and tell the `showNextSlide` function to show in reverse.
