### ISSUE TITLE
Hide last block

### ISSUE THREAD

**Issue by Pantela777** [p-m-p/jquery-box-slider#25]
Exp. I have 3 block for rotate, but different height and when rotated block I see this bug...
http://i.imgur.com/OI7iCE2.png how I can clear...

**Comment by p-m-p** [comment]
Sorry but this plugin does not support slides of different size.

**Comment by ottokupradze** [comment]
Different size ok, but can we hide last block after transform...?

**Comment by Pantela777** [comment]
Different size ok, but can we hide last block after transform...?

**Comment by p-m-p** [comment]
Just give the whole of each slide a background colour.

**Comment by Pantela777** [comment]
Please help me, how I can do it...? http://goo.gl/iK69iI

**Comment by p-m-p** [comment]
Really you need to make each slide the same height. The effect you are using is not designed to support variable sized faces.

**Comment by Pantela777** [comment]
ok, but can we hide last block after transform...?
Exp. only active block I need **display: block;** http://i.imgur.com/UcfxjLx.png
