### ISSUE TITLE
Responsive block

### ISSUE THREAD

**Issue by Pantela777** [p-m-p/jquery-box-slider#26]
I have 100% width block, but when I change browser windows width size my block is didn't work 100% width http://i.imgur.com/x2gL2cX.png but if refresh page, block is set correctly.
How to fix and responsive block.

**Comment by p-m-p** [comment]
Looks like this may be an issue with your CSS implementation. If you post an online example I may be able to help further.

**Comment by Pantela777** [comment]
http://goo.gl/iK69iI

**Comment by p-m-p** [comment]
You are bundling the files separately without the responder module https://github.com/p-m-p/jquery-box-slider/blob/master/js/box-slider-responder.jquery.js

Add this or use one of the minified builds.

**Comment by Pantela777** [comment]
I add but, responsive is not work...
Please help...
